# Generated by Django 2.2.2 on 2019-06-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommApp', '0003_auto_20190626_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Discription',
            field=models.CharField(max_length=1000),
        ),
    ]
